sudo: required
services:
    - docker

before_install:
    - docker build -t danushkarmdc/multi-docker -f ./client/Dockerfile.dev ./client

script:
    - docker run e CI=true danushkarmdc/multi-docker npm test

after_success:
    -docker build -t danushkarmdc/multi-client ./client
    -docker build -t danushkarmdc/multi-nginx ./nginx
    -docker build -t danushkarmdc/multi-server ./server
    -docker build -t danushkarmdc/multi-worker ./worker

    #Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #push images to docker hub
    - docker push danushkarmdc/multi-client
    - docker push danushkarmdc/multi-nginx
    - docker push danushkarmdc/multi-server
    - docker push danushkarmdc/multi-worker